import express from 'express';

// Instantiate the server
const app = express();

// This tells our app to listen for GET messages on the '/' path
// The callback function specifies what the answer will do when a message is received
app.get('/', (req, res) => {
    console.log(req);
    console.log(res); // This will show the default response object generated by Express. We can modify or add to this object before calling res.send()

    res.send('Hello!');
});

// This tells our server to listen to the port 3000
// We can also pass an optional callback function to execute after the server starts
app.listen(3000, () => {
    console.log('Server started at port 3000.')
});

app.post('/submit-data', (req, res) => {
    res.send('Received a POST request');
});